teleop_twist_joy_node:
  ros__parameters: # X-input mode
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.4

    enable_button: 4  # LB shoulder button
    enable_turbo_button: 5  # RB shoulder button
  # ros__parameters: # D-input mode
  #   axis_linear:  # Left thumb stick vertical
  #     x: 1
  #   scale_linear:
  #     x: 0.7
  #   scale_linear_turbo:
  #     x: 1.5
  # 
  #   axis_angular:  # Left thumb stick horizontal
  #     yaw: 0
  #   scale_angular:
  #     yaw: 0.4
  # 
  #   enable_button: 4  # LB shoulder button
  #   enable_turbo_button: 5  # RB shoulder button
  #   enable_turbo_button: 6  # LT shoulder button
